### ISSUE TITLE
you still have null

### ISSUE THREAD

**Issue by LicGabriel05** [MinerCoffee/Miner-Expansion#9]
Every time I want to open a door, open a chest or put a block, the message "you still have null" appears.

**Comment by MinerCoffee** [comment]
Update to the latest build.

**Comment by MinerCoffee** [comment]
> Every time I want to open a door, open a chest or put a block, the message "you still have null" appears.

Let me know if you still are experiencing it.

**Comment by MinerCoffee** [comment]
Fixed in the latest build. https://www.spigotmc.org/resources/miners-expansion.95350/updates
